### ISSUE TITLE
npm auth token is public

### ISSUE THREAD

**Issue by JakeChampion** [rosshadden/dotfiles#1]
You may want to revoke this token via -- https://www.npmjs.com/settings/tokens

https://github.com/rosshadden/dotfiles/blob/2ac994132be4966e61c14ac3cb249eac3cb3e3d1/src/.npmrc

**Comment by rawsp33d** [comment]
Oops. Thanks!

**Comment by rawsp33d** [comment]
Fixed by 35c00f2066013ef1762fb00321d28bdcac5a194f
